version: '3.9'

services:
  mysqldb:
    image: mysql:8.0.29
    user: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: school-db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  spring-service:
    container_name: school-app
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    image: school-app:latest
    ports:
      - "8080:8080"
